baseURL = 'https://jeffvansteijn.nl/'
languageCode = 'en-us'
title = 'Jeff'
theme = 'yaz'

[menu]

      [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = "-100"
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = -200

    
    
    [footer]
  [[menu.footer]]
    identifier = "colophon"
    name = "colophon"
    url = "/colophon/"
    weight = "10"
    
    
    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "assets/images"
    target = "static/images"